### ISSUE TITLE
RE: Install Instructions

### ISSUE THREAD

**Issue by bertrand-caron** [olivierverdier/pydflatex#6]
Hi, Nice project you got going on ;)

I second a previously closed Issue about the lack of install instructions.

You can indeed use `pip`, but you need to provide the git repo as such (took me some googling to find some, might be worth saving other people's time):

```
pip install https://github.com/olivierverdier/pydflatex/zipball/master
```

And while you are there, why not add:

```
pip install blessings
```

Alternatively, why not [submit your package to PyPI](https://packaging.python.org/en/latest/distributing/#uploading-your-project-to-pypi) ?

Cheers, Bertrand

**Comment by olivierverdier** [comment]
Good point. I've added an "Install" section in the readme file in 196a0ade12c412deb873d09638e770b2d496a737. Feel free to reopen or submit a pull request if you have other suggestions.
